In [1]:
import pandas as pd

In [2]:
orders = pd.read_csv("olist_orders_dataset.csv")
order_items = pd.read_csv("olist_order_items_dataset.csv")
order_reviews = pd.read_csv("olist_order_reviews_dataset.csv")
products = pd.read_csv("olist_products_dataset.csv")
customers = pd.read_csv("olist_customers_dataset.csv")
sellers = pd.read_csv("olist_sellers_dataset.csv")
geo = pd.read_csv("olist_geolocation_dataset.csv")
payments = pd.read_csv("olist_order_payments_dataset.csv")

In [3]:
orders["order_purchase_timestamp"] = pd.to_datetime(
    orders["order_purchase_timestamp"],
    format="%Y-%m-%d %H:%M:%S",
    errors="coerce"
)

orders["order_delivered_customer_date"] = pd.to_datetime(
    orders["order_delivered_customer_date"],
    format="%Y-%m-%d %H:%M:%S",
    errors="coerce"
)

orders["order_estimated_delivery_date"] = pd.to_datetime(
    orders["order_estimated_delivery_date"],
    format="%Y-%m-%d %H:%M:%S",
    errors="coerce"
)

### Nivel 2 Pivot Tables con 2 Dimensiones

In [53]:
tabla_cat_prod = pd.merge(products, order_items, on="product_id", how="left")
tabla_cat_prod = pd.merge(tabla_cat_prod, orders[["order_id", "order_status"]], on="order_id", how="left")
pivot = pd.pivot_table(tabla_cat_prod, index="product_category_name", columns="order_status", values="price", aggfunc="sum", fill_value=0)
display(pivot)

order_status,approved,canceled,delivered,invoiced,processing,shipped,unavailable
product_category_name,,,,,,,
agro_industria_e_comercio,0.0,0.00,70566.10,19.50,0.00,1944.87,0.0
alimentos,0.0,149.90,28731.15,0.00,221.60,290.76,0.0
alimentos_bebidas,0.0,60.00,14942.88,62.80,8.00,105.80,0.0
artes,0.0,35.00,23657.30,0.00,224.90,285.44,0.0
artes_e_artesanato,0.0,0.00,1814.01,0.00,0.00,0.00,0.0
...,...,...,...,...,...,...,...
sinalizacao_e_seguranca,0.0,0.00,21315.05,0.00,139.90,54.28,0.0
tablets_impressao_imagem,0.0,0.00,7528.41,0.00,0.00,0.00,0.0
telefonia,0.0,1324.89,309860.23,4654.13,4475.14,3353.14,0.0
telefonia_fixa,0.0,1758.79,55315.21,0.00,2492.50,16.50,0.0
utilidades_domesticas,169.9,5422.86,615628.69,1005.68,1858.23,8163.30,0.0

In [55]:
#7 
tabla_cat_prod = pd.merge(products, order_items, on="product_id", how="left")
tabla_cat_prod = pd.merge(tabla_cat_prod, orders[["order_id", "order_status"]], on="order_id", how="left")
pivot = pd.pivot_table(tabla_cat_prod, index="product_category_name", columns="order_status", values="price", aggfunc="mean", fill_value=0)
display(pivot)

order_status,approved,canceled,delivered,invoiced,processing,shipped,unavailable
product_category_name,,,,,,,
agro_industria_e_comercio,0.0,0.000000,342.553883,19.500000,0.000000,388.974000,0.0
alimentos,0.0,149.900000,57.577455,0.000000,44.320000,58.152000,0.0
alimentos_bebidas,0.0,30.000000,55.549740,15.700000,8.000000,52.900000,0.0
artes,0.0,35.000000,120.087817,0.000000,32.128571,71.360000,0.0
artes_e_artesanato,0.0,0.000000,75.583750,0.000000,0.000000,0.000000,0.0
...,...,...,...,...,...,...,...
sinalizacao_e_seguranca,0.0,0.000000,108.198223,0.000000,139.900000,54.280000,0.0
tablets_impressao_imagem,0.0,0.000000,90.703735,0.000000,0.000000,0.000000,0.0
telefonia,0.0,73.605000,69.945876,221.625238,248.618889,57.812759,0.0
telefonia_fixa,0.0,586.263333,216.922392,0.000000,498.500000,16.500000,0.0
utilidades_domesticas,169.9,110.670612,90.600249,71.834286,68.823333,104.657692,0.0

In [56]:
#8
pivot = pd.pivot_table(tabla_cat_prod, index= "product_category_name", columns= "order_status", values= "freight_value", aggfunc= "mean", fill_value=0)
display(pivot)

order_status,approved,canceled,delivered,invoiced,processing,shipped,unavailable
product_category_name,,,,,,,
agro_industria_e_comercio,0.00,0.000000,27.365049,8.720000,0.000000,39.536000,0.0
alimentos,0.00,17.760000,14.155371,0.000000,15.614000,22.334000,0.0
alimentos_bebidas,0.00,9.685000,16.337881,11.850000,14.520000,15.905000,0.0
artes,0.00,16.600000,19.432640,0.000000,19.108571,16.645000,0.0
artes_e_artesanato,0.00,0.000000,15.422083,0.000000,0.000000,0.000000,0.0
...,...,...,...,...,...,...,...
sinalizacao_e_seguranca,0.00,0.000000,32.880914,0.000000,18.550000,11.730000,0.0
tablets_impressao_imagem,0.00,0.000000,14.773494,0.000000,0.000000,0.000000,0.0
telefonia,0.00,14.022778,15.652910,12.056190,21.676667,16.855690,0.0
telefonia_fixa,0.00,15.990000,17.652275,0.000000,14.880000,14.110000,0.0
utilidades_domesticas,9.56,19.178980,21.010090,18.502857,13.631852,23.193846,0.0

In [ ]:
base = order_items.merge(products[["product_id", "product_category_name"]], on="product_id", how="left") \
.merge(orders[["order_id", "order_status"]], on="order_id", how="left")

In [38]:
#9
tabla_original = base.pivot_table(index="product_category_name", columns="order_status", values="price", aggfunc="sum")
tabla_fill0 = base.pivot_table(index="product_category_name", columns="order_status", values="price", aggfunc="sum", fill_value=0)
tabla_original.isna().sum().sum()

np.int64(237)

In [39]:
#10
base.pivot_table(index=["product_category_name", "order_status"], values="price", aggfunc="mean")

                                             price
product_category_name     order_status
agro_industria_e_comercio delivered     342.553883
                          invoiced       19.500000
                          shipped       388.974000
alimentos                 canceled      149.900000
                          delivered      57.577455
...                                            ...
utilidades_domesticas     canceled      110.670612
                          delivered      90.600249
                          invoiced       71.834286
                          processing     68.823333
                          shipped       104.657692

[274 rows x 1 columns]

In [40]:
#11 
base["total"] = base["price"] + base["freight_value"]
display(base["total"])

0          72.19
1         259.83
2         216.87
3          25.78
4         218.04
           ...
112645    343.40
112646    386.53
112647    116.85
112648     64.71
112649     55.79
Name: total, Length: 112650, dtype: float64

In [41]:
# 12
base["categoria_precio"] = base["price"].apply(lambda x: 'caro' if x > 100 else 'barato')
display(base["categoria_precio"])

0         barato
1           caro
2           caro
3         barato
4           caro
           ...
112645      caro
112646      caro
112647    barato
112648    barato
112649    barato
Name: categoria_precio, Length: 112650, dtype: str

In [42]:
# 13
base["flete_alto"] = base.apply(lambda row: row["freight_value"] > 0.2 * row["price"], axis=1)
display(base["flete_alto"])

0          True
1         False
2         False
3          True
4         False
          ...
112645    False
112646    False
112647    False
112648    False
112649     True
Name: flete_alto, Length: 112650, dtype: bool

In [43]:
# 14
base["categoria_mayus"] = base["product_category_name"].apply(lambda x: x.upper() if pd.notna(x) else x)
display(base["categoria_mayus"])

0                     COOL_STUFF
1                       PET_SHOP
2               MOVEIS_DECORACAO
3                     PERFUMARIA
4             FERRAMENTAS_JARDIM
                   ...
112645     UTILIDADES_DOMESTICAS
112646    INFORMATICA_ACESSORIOS
112647             ESPORTE_LAZER
112648    INFORMATICA_ACESSORIOS
112649           CAMA_MESA_BANHO
Name: categoria_mayus, Length: 112650, dtype: str

In [44]:
# 15
base["contiene_palabra"] = base["product_category_name"].apply(lambda x: 'beleza' in x if pd.notna(x) else False)
display(base["contiene_palabra"])

0         False
1         False
2         False
3         False
4         False
          ...
112645    False
112646    False
112647    False
112648    False
112649    False
Name: contiene_palabra, Length: 112650, dtype: bool

In [46]:
# 16
base["segmento_costo"] = base["total"].apply(lambda x: 'alto' if x > 150 else 'bajo')
base.pivot_table(index="product_category_name", columns="segmento_costo", values="total", aggfunc="mean")

segmento_costo                   alto       bajo
product_category_name
agro_industria_e_comercio  594.816992  58.557079
alimentos                  187.630244  61.773134
alimentos_bebidas          247.710000  54.104055
artes                      409.736429  92.680608
artes_e_artesanato         257.580000  67.209524
...                               ...        ...
sinalizacao_e_seguranca    316.602069  68.469007
tablets_impressao_imagem   423.133333  93.565125
telefonia                  334.555756  47.613979
telefonia_fixa             649.446667  63.473388
utilidades_domesticas      268.619237  67.945602

[73 rows x 2 columns]

In [45]:
#17
base["pct_envio"] = base["freight_value"] / base["price"]
base["clasificacion_envio"] = base["pct_envio"].apply(lambda x: 'envío alto' if x > 0.2 else 'envío bajo')
base.pivot_table(index="clasificacion_envio", values="price", aggfunc=["mean", "count"])

                           mean  count
                          price  price
clasificacion_envio
envío alto            57.894930  63800
envío bajo           202.619184  48850

In [47]:
#18
precio_promedio_global = base["price"].mean()
base["sobre_promedio"] = base["price"].apply(lambda x: x > precio_promedio_global)
base.pivot_table(index="sobre_promedio", values="price", aggfunc=["mean", "count"])

                      mean  count
                     price  price
sobre_promedio
False            57.643243  80522
True            278.576149  32128

In [48]:
#19
base.pivot_table(index="product_category_name", values="freight_value", aggfunc=["sum", "mean"])

                                    sum          mean
                          freight_value freight_value
product_category_name
agro_industria_e_comercio       5843.60     27.564151
alimentos                       7271.03     14.256922
alimentos_bebidas               4507.99     16.215791
artes                           4045.17     19.354880
artes_e_artesanato               370.13     15.422083
...                                 ...           ...
sinalizacao_e_seguranca         6507.82     32.702613
tablets_impressao_imagem        1226.20     14.773494
telefonia                      71215.79     15.669041
telefonia_fixa                  4637.81     17.567462
utilidades_domesticas         146149.11     20.986374

[73 rows x 2 columns]

In [59]:
#20
base["categoria_precio"] = base["price"].apply(lambda x: 'caro' if x > 100 else 'barato')
base["pct_envio"] = base["freight_value"] / base["price"]
tabla_20 = base.pivot_table(index="product_category_name", columns="categoria_precio", values="pct_envio", aggfunc="mean")
display(tabla_20)

categoria_precio             barato      caro
product_category_name
agro_industria_e_comercio  0.562946  0.081024
alimentos                  0.373673  0.132043
alimentos_bebidas          0.548580  0.137392
artes                      0.340134  0.154773
artes_e_artesanato         0.501647  0.140116
...                             ...       ...
sinalizacao_e_seguranca    0.677226  0.320076
tablets_impressao_imagem   0.232579  0.114296
telefonia                  0.583644  0.101207
telefonia_fixa             0.597537  0.090256
utilidades_domesticas      0.484402  0.182242

[73 rows x 2 columns]

In [60]:
#21
base["ratio_envio_precio"] = base.apply(lambda row: row["freight_value"] / row["price"] if row["price"] > 0 else None, axis=1)
base.pivot_table(index="product_category_name", values="ratio_envio_precio", aggfunc="mean").sort_values("ratio_envio_precio", ascending=False)

                                ratio_envio_precio
product_category_name
casa_conforto_2                           0.933862
dvds_blu_ray                              0.833045
eletronicos                               0.683517
artigos_de_natal                          0.675660
fashion_underwear_e_moda_praia            0.565503
...                                            ...
relogios_presentes                        0.170581
portateis_casa_forno_e_cafe               0.164350
seguros_e_servicos                        0.147548
pc_gamer                                  0.096556
pcs                                       0.056613

[73 rows x 1 columns]

In [61]:
#22
tabla_precio_estado = base.pivot_table(index="product_category_name", columns="order_status", values="price", aggfunc="mean")
base["flete_alto"] = base.apply(lambda row: row["freight_value"] > 0.2 * row["price"], axis=1)
tabla_flete_estado = base.pivot_table(index="product_category_name", columns="order_status", values="flete_alto", aggfunc="mean")
display(tabla_flete_estado)

order_status,approved,canceled,delivered,invoiced,processing,shipped,unavailable
product_category_name,,,,,,,
agro_industria_e_comercio,NaN,NaN,0.368932,1.000000,NaN,0.200000,NaN
alimentos,NaN,0.000000,0.741483,NaN,1.000000,1.000000,NaN
alimentos_bebidas,NaN,1.000000,0.828996,1.000000,1.000000,1.000000,NaN
artes,NaN,1.000000,0.517766,NaN,1.000000,0.750000,NaN
artes_e_artesanato,NaN,NaN,0.583333,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
sinalizacao_e_seguranca,NaN,NaN,0.695431,NaN,0.000000,1.000000,NaN
tablets_impressao_imagem,NaN,NaN,0.337349,NaN,NaN,NaN,NaN
telefonia,NaN,0.722222,0.791422,0.333333,0.444444,0.793103,NaN
telefonia_fixa,NaN,0.000000,0.560784,NaN,0.000000,1.000000,NaN
utilidades_domesticas,0.0,0.693878,0.692127,0.857143,0.518519,0.615385,NaN

In [62]:
#Reto 
base["segmento_precio"] = base["price"].apply(lambda x: "caro" if x > 100 else "barato")
base["ratio_envio_precio"] = base.apply(
    lambda row: row["freight_value"] / row["price"] if row["price"] > 0 else None,
    axis=1)
resumen_direccion = base.pivot_table(index=["product_category_name", "segmento_precio"], columns="order_status", values=["price", "freight_value", "ratio_envio_precio"], aggfunc={"price": "mean", "freight_value": "mean", "ratio_envio_precio": "mean"}, fill_value=0)
display(resumen_direccion)

                                          freight_value                        \
order_status                                   approved   canceled  delivered
product_category_name     segmento_precio
agro_industria_e_comercio barato                   0.00   0.000000  17.004337
                          caro                     0.00   0.000000  34.356423
alimentos                 barato                   0.00   0.000000  13.536107
                          caro                     0.00  17.760000  19.478654
alimentos_bebidas         barato                   0.00   9.685000  15.507702
...                                                 ...        ...        ...
telefonia                 caro                     0.00  17.280000  21.543133
telefonia_fixa            barato                   0.00   8.460000  14.485263
                          caro                     0.00  19.755000  22.325922
utilidades_domesticas     barato                   0.00  14.739487  16.440349
                          caro                     9.56  36.493000  33.334467

                                                                            \
order_status                                invoiced processing    shipped
product_category_name     segmento_precio
agro_industria_e_comercio barato            8.720000   0.000000  27.360000
                          caro              0.000000   0.000000  42.580000
alimentos                 barato            0.000000  15.614000  18.415000
                          caro              0.000000   0.000000  38.010000
alimentos_bebidas         barato           11.850000  14.520000  15.905000
...                                              ...        ...        ...
telefonia                 caro             13.543636  24.422000  18.068889
telefonia_fixa            barato            0.000000   0.000000  14.110000
                          caro              0.000000  14.880000   0.000000
utilidades_domesticas     barato           18.907692  12.470000  17.066471
                          caro             13.240000  16.951429  34.767778

                                                         price              \
order_status                              unavailable approved    canceled
product_category_name     segmento_precio
agro_industria_e_comercio barato                  0.0      0.0    0.000000
                          caro                    0.0      0.0    0.000000
alimentos                 barato                  0.0      0.0    0.000000
                          caro                    0.0      0.0  149.900000
alimentos_bebidas         barato                  0.0      0.0   30.000000
...                                               ...      ...         ...
telefonia                 caro                    0.0      0.0  253.263333
telefonia_fixa            barato                  0.0      0.0   99.900000
                          caro                    0.0      0.0  829.445000
utilidades_domesticas     barato                  0.0      0.0   45.959487
                          caro                    0.0    169.9  363.044000

                                                       ...              \
order_status                                delivered  ...  processing
product_category_name     segmento_precio              ...
agro_industria_e_comercio barato            38.040361  ...    0.000000
                          caro             548.038618  ...    0.000000
alimentos                 barato            46.358300  ...   44.320000
                          caro             154.019038  ...    0.000000
alimentos_bebidas         barato            35.591830  ...    8.000000
...                                               ...  ...         ...
telefonia                 caro             280.498155  ...  416.430000
telefonia_fixa            barato            35.275000  ...    0.000000
                          caro             484.984563  ...  498.500000
utilidades_domesticas     barato            46.680038  ...   41.060000
                          caro             209.051001  ...  148.147143

                                                                   \
order_status                                  shipped unavailable
product_category_name     segmento_precio
agro_industria_e_comercio barato            57.880000         0.0
                          caro             471.747500         0.0
alimentos                 barato            35.215000         0.0
                          caro             149.900000         0.0
alimentos_bebidas         barato            52.900000         0.0
...                                               ...         ...
telefonia                 caro             208.865556         0.0
telefonia_fixa            barato            16.500000         0.0
                          caro               0.000000         0.0
utilidades_domesticas     barato            50.823333         0.0
                          caro             206.344815         0.0

                                          ratio_envio_precio            \
order_status                                        approved  canceled
product_category_name     segmento_precio
agro_industria_e_comercio barato                    0.000000  0.000000
                          caro                      0.000000  0.000000
alimentos                 barato                    0.000000  0.000000
                          caro                      0.000000  0.118479
alimentos_bebidas         barato                    0.000000  0.339343
...                                                      ...       ...
telefonia                 caro                      0.000000  0.084732
telefonia_fixa            barato                    0.000000  0.084685
                          caro                      0.000000  0.039265
utilidades_domesticas     barato                    0.000000  0.619204
                          caro                      0.056268  0.132323

                                                                          \
order_status                              delivered  invoiced processing
product_category_name     segmento_precio
agro_industria_e_comercio barato           0.565428  0.447179   0.000000
                          caro             0.080748  0.000000   0.000000
alimentos                 barato           0.370864  0.000000   0.353520
                          caro             0.129967  0.000000   0.000000
alimentos_bebidas         barato           0.542905  0.787492   1.815000
...                                             ...       ...        ...
telefonia                 caro             0.102271  0.055836   0.086351
telefonia_fixa            barato           0.599216  0.000000   0.000000
                          caro             0.094178  0.000000   0.029850
utilidades_domesticas     barato           0.484552  0.295071   0.530401
                          caro             0.182889  0.083270   0.116891


order_status                                shipped unavailable
product_category_name     segmento_precio
agro_industria_e_comercio barato           0.472702         0.0
                          caro             0.089516         0.0
alimentos                 barato           0.712826         0.0
                          caro             0.253569         0.0
alimentos_bebidas         barato           0.313633         0.0
...                                             ...         ...
telefonia                 caro             0.096016         0.0
telefonia_fixa            barato           0.855152         0.0
                          caro             0.000000         0.0
utilidades_domesticas     barato           0.396995         0.0
                          caro             0.181942         0.0

[143 rows x 21 columns]